Resources:
  Type: AWS::S3::Bucket
  Properties: 
    BucketName: mys3-demo-8877-cicd
    VersioningConfiguration:
        Status: Disabled
    Tags: 
      - Key: "keyname1"
        Value: "value1"
      - Key: "keyname2"
        Value: "value2"